name: build package
on:
  push:
    branches: [ master, ghapoc ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
#    container: archlinux:base-devel
    steps:
      # - name: Prepare
      #   run: |
      #     pacman-key --init
      #     pacman -Syu --noconfirm
      #     pacman -S --noconfirm git meson clang glslang libcap wlroots \
      #       sdl2 vulkan-headers libx11 libxcomposite libxrender libxres \
      #       libxtst libxkbcommon libdrm libinput wayland-protocols \
      #       xorg-xwayland pipewire
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: container apt cache
        uses: actions/cache@v3
        with:
          path: ubuntu_22.04/.cache
          key: ubuntu_22.04-apt-cache

      - name: Build deps cache
        run: |
          cd ubuntu_22.04/01-deps
          make image
          sudo chmod -R a+r ../.cache

      - name: container apt cache save
        uses: actions/cache/save@v3
        with:
          path: ubuntu_22.04/.cache
          key: ubuntu_22.04-apt-cache

      - name: deps cache
        uses: actions/cache@v3
        with:
          path: ubuntu_22.04/01-deps/packages
          key: ubuntu_22.04-deps-cache

      - name: Build deps
        run: |
          cd ubuntu_22.04/01-deps
          make 
